// <auto-generated />
using System;
using EBM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EBM.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250522120624_SyncBlokeEdenAraciFix")]
    partial class SyncBlokeEdenAraciFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EBM.Models.AcikArtirma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AraciId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("KazananFirmaId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("KazanilanFiyat")
                        .HasColumnType("numeric");

                    b.Property<int>("MalzemeId")
                        .HasColumnType("integer");

                    b.Property<int?>("SatinAlimId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AraciId");

                    b.HasIndex("KazananFirmaId");

                    b.HasIndex("MalzemeId")
                        .IsUnique();

                    b.HasIndex("SatinAlimId");

                    b.ToTable("AcikArtirmalar");
                });

            modelBuilder.Entity("EBM.Models.GeridonusumMalzemesi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BlokeEdenAraciId")
                        .HasColumnType("integer");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KazandigiCip")
                        .HasColumnType("integer");

                    b.Property<float>("MiktarKg")
                        .HasColumnType("real");

                    b.Property<int>("MusteriId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Turu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BlokeEdenAraciId");

                    b.HasIndex("MusteriId");

                    b.ToTable("Malzemeler");
                });

            modelBuilder.Entity("EBM.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CipBakiye")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("ParaBakiye")
                        .HasColumnType("numeric");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("EBM.Models.Odul", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("AlinmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GerekliCip")
                        .HasColumnType("integer");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Oduller");
                });

            modelBuilder.Entity("EBM.Models.SatinAlim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AraciId")
                        .HasColumnType("integer");

                    b.Property<int>("MalzemeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VerilenCip")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AraciId");

                    b.HasIndex("MalzemeId")
                        .IsUnique();

                    b.ToTable("SatinAlimlar");
                });

            modelBuilder.Entity("EBM.Models.Teklif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcikArtirmaId")
                        .HasColumnType("integer");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TeklifTutar")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AcikArtirmaId");

                    b.HasIndex("FirmaId");

                    b.ToTable("Teklifler");
                });

            modelBuilder.Entity("EBM.Models.AcikArtirma", b =>
                {
                    b.HasOne("EBM.Models.Kullanici", "Araci")
                        .WithMany("AcikArtirmalar")
                        .HasForeignKey("AraciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EBM.Models.Kullanici", "KazananFirma")
                        .WithMany()
                        .HasForeignKey("KazananFirmaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EBM.Models.GeridonusumMalzemesi", "Malzeme")
                        .WithOne("AcikArtirma")
                        .HasForeignKey("EBM.Models.AcikArtirma", "MalzemeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EBM.Models.SatinAlim", null)
                        .WithMany("AcikArtirmalar")
                        .HasForeignKey("SatinAlimId");

                    b.Navigation("Araci");

                    b.Navigation("KazananFirma");

                    b.Navigation("Malzeme");
                });

            modelBuilder.Entity("EBM.Models.GeridonusumMalzemesi", b =>
                {
                    b.HasOne("EBM.Models.Kullanici", "BlokeEdenAraci")
                        .WithMany()
                        .HasForeignKey("BlokeEdenAraciId");

                    b.HasOne("EBM.Models.Kullanici", "Musteri")
                        .WithMany("Malzemeler")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BlokeEdenAraci");

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("EBM.Models.Odul", b =>
                {
                    b.HasOne("EBM.Models.Kullanici", "Kullanici")
                        .WithMany("Oduller")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("EBM.Models.SatinAlim", b =>
                {
                    b.HasOne("EBM.Models.Kullanici", "Araci")
                        .WithMany("SatinAlimlar")
                        .HasForeignKey("AraciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EBM.Models.GeridonusumMalzemesi", "Malzeme")
                        .WithOne("SatinAlim")
                        .HasForeignKey("EBM.Models.SatinAlim", "MalzemeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Araci");

                    b.Navigation("Malzeme");
                });

            modelBuilder.Entity("EBM.Models.Teklif", b =>
                {
                    b.HasOne("EBM.Models.AcikArtirma", "AcikArtirma")
                        .WithMany("Teklifler")
                        .HasForeignKey("AcikArtirmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EBM.Models.Kullanici", "Firma")
                        .WithMany("Teklifler")
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcikArtirma");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("EBM.Models.AcikArtirma", b =>
                {
                    b.Navigation("Teklifler");
                });

            modelBuilder.Entity("EBM.Models.GeridonusumMalzemesi", b =>
                {
                    b.Navigation("AcikArtirma")
                        .IsRequired();

                    b.Navigation("SatinAlim")
                        .IsRequired();
                });

            modelBuilder.Entity("EBM.Models.Kullanici", b =>
                {
                    b.Navigation("AcikArtirmalar");

                    b.Navigation("Malzemeler");

                    b.Navigation("Oduller");

                    b.Navigation("SatinAlimlar");

                    b.Navigation("Teklifler");
                });

            modelBuilder.Entity("EBM.Models.SatinAlim", b =>
                {
                    b.Navigation("AcikArtirmalar");
                });
#pragma warning restore 612, 618
        }
    }
}
